#!/bind/bash
#REM moitrijer

. ./00_variables.sh

cp /etc/bind/named.conf.local /etc/bind/named.conf.local.bak

cat << EOF > /etc/bind/named.conf.local

zone "$DOMINIO_COM" {
	type master;
	file "db.$DOMINIO_COM";
};

zone "$IP_REVER.in-addr.arpa" {
	type master;
	file "db.$IP_DB";
};
EOF

cp /etc/bind/db.empty /var/cache/bind/db.$DOMINIO_COM

cat <<EOF> /var/cache/bind/db.$DOMINIO_COM
; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
\$TTL	86400
@	IN	SOA	$DOMINIO_COM. root.$DOMINIO_COM. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	ns.$DOMINIO_COM.
ns		A	$DNS
$NOMBRE_D	A	$DNS
$NOMBRE_CLI1	A	$IP_CLI1
EOF

cp /etc/bind/db.empty /var/cache/bind/db.$IP_DB

cat <<EOF> /var/cache/bind/db.$IP_DB
; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
\$TTL	86400
@	IN	SOA	$DOMINIO_COM. root.$DOMINIO_COM. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	ns.$DOMINIO_COM.
$IP_FIN_D		PTR	ns.$DOMINIO_COM.
		PTR	$NOMBRE_D.$DOMINIO_COM.
$IP_FIN_U1		PTR	$NOMBRE_CLI1.$DOMINIO_COM.
EOF
